const { mdToPdf } = require('md-to-pdf');
const fs = require('fs').promises;
const path = require('path');

const PROMPTS_DIR = path.join(__dirname, '..', 'prompts');
const OUTPUT_DIR = path.join(__dirname, '..', 'deliverables');
const CSS_FILE = path.join(__dirname, 'pdf-styles.css');

const PROMPT_FILES = [
  'marketing-prompts.md',
  'content-writing-prompts.md',
  'coding-prompts.md',
  'business-prompts.md',
  'creative-prompts.md',
  'productivity-prompts.md'
];

async function ensureDir(dir) {
  try {
    await fs.mkdir(dir, { recursive: true });
  } catch (err) {
    if (err.code !== 'EEXIST') throw err;
  }
}

function extractPromptsAsText(markdown) {
  const lines = markdown.split('\n');
  let result = [];
  let inCodeBlock = false;
  let currentSection = '';
  let currentPromptNum = '';

  for (const line of lines) {
    if (line.startsWith('# ')) {
      result.push('=' .repeat(60));
      result.push(line.substring(2).toUpperCase());
      result.push('=' .repeat(60));
      result.push('');
    } else if (line.startsWith('## ')) {
      result.push('');
      result.push('-'.repeat(50));
      currentSection = line.substring(3);
      result.push(currentSection);
      result.push('-'.repeat(50));
      result.push('');
    } else if (line.startsWith('### ')) {
      result.push('');
      currentPromptNum = line.substring(4);
      result.push(`>>> ${currentPromptNum}`);
      result.push('');
    } else if (line.startsWith('```')) {
      if (!inCodeBlock) {
        result.push('[PROMPT START]');
        result.push('');
      } else {
        result.push('');
        result.push('[PROMPT END]');
        result.push('');
      }
      inCodeBlock = !inCodeBlock;
    } else if (inCodeBlock) {
      result.push(line);
    } else if (line.startsWith('**Tips') || line.startsWith('**Example Output')) {
      result.push(line.replace(/\*\*/g, ''));
    }
  }

  result.push('');
  result.push('='.repeat(60));
  result.push('Generated by PerfectPrompts.ai');
  result.push('='.repeat(60));

  return result.join('\n');
}

async function convertFile(filename) {
  const inputPath = path.join(PROMPTS_DIR, filename);
  const baseName = filename.replace('.md', '');
  const pdfOutput = path.join(OUTPUT_DIR, 'pdf', `${baseName}.pdf`);
  const txtOutput = path.join(OUTPUT_DIR, 'txt', `${baseName}.txt`);

  console.log(`Converting: ${filename}`);

  const markdown = await fs.readFile(inputPath, 'utf-8');
  const cssContent = await fs.readFile(CSS_FILE, 'utf-8');

  try {
    const pdf = await mdToPdf(
      { content: markdown },
      {
        css: cssContent,
        pdf_options: {
          format: 'Letter',
          margin: {
            top: '0.75in',
            right: '0.75in',
            bottom: '0.75in',
            left: '0.75in'
          },
          printBackground: true
        },
        launch_options: {
          args: ['--no-sandbox']
        }
      }
    );

    if (pdf) {
      await fs.writeFile(pdfOutput, pdf.content);
      console.log(`  ✓ PDF: ${pdfOutput}`);
    }
  } catch (err) {
    console.error(`  ✗ PDF Error: ${err.message}`);
  }

  const txtContent = extractPromptsAsText(markdown);
  await fs.writeFile(txtOutput, txtContent);
  console.log(`  ✓ TXT: ${txtOutput}`);
}

async function main() {
  console.log('\n🚀 PerfectPrompts.ai - Converting prompt packs\n');

  await ensureDir(path.join(OUTPUT_DIR, 'pdf'));
  await ensureDir(path.join(OUTPUT_DIR, 'txt'));

  for (const file of PROMPT_FILES) {
    await convertFile(file);
    console.log('');
  }

  console.log('✅ Conversion complete!\n');
  console.log(`Output directory: ${OUTPUT_DIR}`);
}

main().catch(console.error);
